# Site settings
title: Yu Jinlin
description: Hello World
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yu Jinlin
user_description: If you wish to succeed, you should use persistence as your good friend, experience as your reference, prudence as your brother and hope as your sentry.
user_title: Software Developer
email: jenly1314@gamil.com
twitter_username: jenly1314
github_username: jenly1314
gplus_username: jenly1314

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
